// <auto-generated />
namespace Library_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ZBZ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZBZ));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141358486_ZBZ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
